#!/usr/bin/env php
<?php
declare(strict_types=1);

use T2\Config;
use T2\Console\Command;

if (!Phar::running()) {
    chdir(__DIR__);
}
require_once __DIR__ . '/vendor/autoload.php';
if (!$appConfigFile = config_path('app.php')) {
    throw new RuntimeException('Config file not found: app.php');
}
$appConfig = require $appConfigFile;
if ($timezone = $appConfig['default_timezone'] ?? '') {
    date_default_timezone_set($timezone);
}
if (!in_array($argv[1] ?? '', ['start', 'restart', 'stop', 'status', 'reload', 'connections'])) {
    require_once __DIR__ . '/vendor/phpmarket/t2-framework/src/App/bootstrap.php';
} else {
    if (class_exists('App\App')) {
        App\App::loadAllConfig(['route']);
    } else {
        Config::reload(config_path(), ['route', 'container']);
    }
}
$cli = new Command();
$cli->setName('T2Engine cli');
$cli->installInternalCommands();
$cli->run();
